const data = [
  {
    id: 1,
    CarModel: "Koenigsegg",
    CarYoqilgi: "90",
    ispopular: true,
    CarPeopleSoni: "4",
    CarMoney: "99.00",
    CarIsLike: false,
  },
  {
    id: 2,
    CarModel: "Nissan GT - R",
    CarYoqilgi: "90",
    ispopular: true,
    CarPeopleSoni: "4",
    CarMoney: "99.00",
    CarIsLike: false,
  },
  {
    id: 3,
    CarModel: "Rolls - Royce",
    CarYoqilgi: "90",
    ispopular: true,
    CarPeopleSoni: "4",
    CarMoney: "99.00",
    CarIsLike: false,
  },
  {
    id: 4,
    CarModel: "Nissan GT - R",
    CarYoqilgi: "90",
    ispopular: true,
    CarPeopleSoni: "4",
    CarMoney: "99.00",
    CarIsLike: false,
  },

  {
    id: 5,
    CarModel: "All New Rush",
    CarYoqilgi: "90",
    CarPeopleSoni: "4",
    CarMoney: "99.00",
    ispopular: false,
    CarIsLike: false,
  },
  {
    id: 6,
    CarModel: "CR  - V",
    CarYoqilgi: "90",
    CarPeopleSoni: "4",
    ispopular: false,
    CarMoney: "99.00",
    CarIsLike: false,
  },
  {
    id: 7,
    CarModel: "All New Terios",
    CarYoqilgi: "90",
    CarPeopleSoni: "4",
    ispopular: false,
    CarMoney: "99.00",
    CarIsLike: false,
  },
  {
    id: 8,
    CarModel: "CR  - V",
    CarYoqilgi: "90",
    CarPeopleSoni: "4",
    CarMoney: "99.00",
    ispopular: false,
    CarIsLike: false,
  },
  {
    id: 9,
    CarModel: "MG ZX Exclusice",
    CarYoqilgi: "90",
    CarPeopleSoni: "4",
    CarMoney: "99.00",
    CarIsLike: false,
    ispopular: false,
  },
  {
    id: 10,
    CarModel: "New MG ZS",
    CarYoqilgi: "90",
    CarPeopleSoni: "4",
    CarMoney: "99.00",
    CarIsLike: false,
    ispopular: false,
  },
  {
    id: 11,
    CarModel: "MG ZX Excite",
    CarYoqilgi: "90",
    CarPeopleSoni: "4",
    CarMoney: "99.00",
    CarIsLike: false,
    ispopular: false,
  },
  {
    id: 12,
    CarModel: "New MG ZS",
    CarYoqilgi: "90",
    CarPeopleSoni: "4",
    CarMoney: "99.00",
    CarIsLike: false,
    ispopular: false,
  },
  
];

export default data;
